### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by potato23333** [SKSKSK94/Distributed_SAC#1]
Hi, I was using your code on windows. The error information is as follows:
`redis.exceptions.AuthenticationError: Authentication required. Could you please help me, thanks.
`

**Comment by SKSKSK94** [comment]
Hello.

My test environment is as follows:
- CPU : i7-6700k
- GPU : GTX 1080
- OS : Ubuntu 18.04

I've never run the codes on windows. So I recommend you to run the codes on Ubuntu.

Temporarily, the issue can be fixed by following this:

1. Modify `learner.py` codes 
`
self.server = redis.StrictRedis(host='localhost', password='5241590000000000')
`

2. Modify `player.py` codes 
`
self.server = redis.StrictRedis(host='localhost', password='5241590000000000')
`

If this still gives errors, install [redis window version](https://github.com/microsoftarchive/redis/releases)

Thank you.

**Comment by potato23333** [comment]
It works, thank you!

**Comment by potato23333** [comment]
Hi, sorry to bother you again. I want to ask how did you get the metadata. Thanks!

**Comment by SKSKSK94** [comment]
1. You should install fairseq to use pre-trained roberta
    Follow the installation : https://github.com/pytorch/fairseq
2. You can download pre-trained roberta base model 
    ```bash
    # Download roberta.base model
    wget https://dl.fbaipublicfiles.com/fairseq/models/roberta.base.tar.gz
    tar -xzvf roberta.base.tar.gz
    ```
    Reference : https://github.com/pytorch/fairseq/tree/main/examples/roberta#load-roberta-for-pytorch-10-or-custom-models
3. Use the following codes (you may modify some parts of the codes, especially path of json and pre-trained model files)
    ```python
    import torch
    import json
    import numpy as np
    from fairseq.models.roberta import RobertaModel

    roberta = RobertaModel.from_pretrained('./roberta.base.tar.gz', checkpoint_file='model.pt')
    roberta.eval()  # disable dropout (or leave in train mode to finetune)

    MT10_task_name = ['reach-v2', 'push-v2', 'pick-place-v2', 'door-open-v2', 'drawer-open-v2', 'drawer-close-v2', 'button-press-    topdown-v2', 'peg-insert-side-v2', 'window-open-v2', 'window-close-v2']

    with open('task_metadata.json', 'r') as f:
        task_name2metadata = json.load(f)

    task_name2vector = {}
    for name in MT10_task_name:
        metadata = task_name2metadata[name]
        tokens = roberta.encode(metadata)
        last_layer_features = roberta.extract_features(tokens)
        task_name2vector[name] = last_layer_features.mean(dim=1).squeeze(dim=0).detach().cpu().numpy().tolist()

    with open('mt10_pretrained_embedding.json', 'w') as f:
        json.dump(task_name2vector, f)
   ```
   Reference : https://github.com/pytorch/fairseq/tree/main/examples/roberta#extract-features-from-roberta

I hope this works!

**Comment by potato23333** [comment]
For the `task_metadata.json`, does it contain only the name of the environments or also includes other information? Could you give a example, thanks!

**Comment by SKSKSK94** [comment]
This is the `task_metadata.json' file which only describes tasks.
```json
{
    "reach-v2" : "Reach a goal position.",
    "push-v2" : "Push the puck to a goal.",
    "pick-place-v2" : "Pick and place a puck to a goal.",
    "door-open-v2" : "Open a door with a revolving joint.",
    "drawer-open-v2" : "Open a drawer.",
    "drawer-close-v2" : "Push and close a drawer.",
    "button-press-topdown-v2" : "Press a button from the top.",
    "peg-insert-side-v2" : "Insert a peg sideways.",
    "window-open-v2" : "Push and open a window.",
    "window-close-v2" : "Push and close a window."
}
```
I hope it is helpful for you.

**Comment by potato23333** [comment]
Thank you for your timely reply, thanks!

**Comment by Lizhanqing-2697** [comment]
Hello, can I ask what specific versions of packages are needed in the environment?
